pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.ResourceGeneration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: "Git Setup"
  continueOnError: true
  env:
    UserName: $(GitHubUser)
    Password: $(GitHubPat)
  inputs:
    targetType: 'inline'
    failOnStderr: false
    pwsh: true
    ignoreLASTEXITCODE: true
    script: 'git config --global user.email "azure-pipeline@materialdesigninxaml.net/" 2>$null
      
      git config --global user.name "Azure Pipeline" 2>$null

      git remote set-url origin https://$env:UserName:$env:Password@github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit.git 2>$null
      
      Write-Host "Before checkout"

      git checkout -b pipeline/icons 2>$null
      
      Write-Host "LEC $LASTEXITCODE"'



- powershell: .paket\paket.exe restore

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: "Generate Icons"
  inputs:
    targetType: 'inline'
    script: '.\\mdresgen.exe icons'
    workingDirectory: '.\\mdresgen\\bin\\$(buildConfiguration)'

- task: PowerShell@2
  displayName: "Commit Updated Icons"
  inputs:
    targetType: 'inline'
    script: 'git commit -a -m "Icons update from Azure pipeline"
      
      git push -f -u HEAD'

- task: PublishPipelineArtifact@0
  name: "PublishResourceGenerator"
  enabled: "false"
  inputs:
    artifactName: 'ResourceGenerator'
    targetPath: 'mdresgen/bin/Release'