pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'MaterialDesignToolkit.ResourceGeneration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- powershell: .paket\paket.exe restore

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: "Generate Icons"
  inputs:
    targetType: 'inline'
    script: '.\\mdresgen\\bin\\$(buildConfiguration)\\mdresgen.exe icons'

- task: PublishPipelineArtifact@0
  name: "PublishResourceGenerator"
  enabled: "false"
  inputs:
    artifactName: 'ResourceGenerator'
    targetPath: 'mdresgen/bin/Release'