pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'MaterialDesignToolkit.ResourceGeneration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  persistCredentials: "true"

- powershell: .paket\paket.exe restore

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- powershell: git checkout -b pipeline/icons

- task: PowerShell@2
  displayName: "Generate Icons"
  inputs:
    targetType: 'inline'
    script: '.\\mdresgen.exe icons'
    workingDirectory: '.\\mdresgen\\bin\\$(buildConfiguration)'

- powershell: git commit -a -m "Icons update from Azure pipeline"

- powershell: git push -f origin pipeline/icons

- task: PublishPipelineArtifact@0
  name: "PublishResourceGenerator"
  enabled: "false"
  inputs:
    artifactName: 'ResourceGenerator'
    targetPath: 'mdresgen/bin/Release'