pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.ResourceGeneration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  displayName: "Git Clean"
  inputs:
    targetType: 'inline'
    script: 'git clean -f
      
      git branch -f pipeline/icons | Write-Host
      
      git checkout -f pipeline/icons | Write-Host'

- powershell: .paket\paket.exe restore

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  displayName: "Generate Icons"
  inputs:
    targetType: 'inline'
    script: '.\\mdresgen.exe icons'
    workingDirectory: '.\\mdresgen\\bin\\$(buildConfiguration)'

- task: PowerShell@2
  displayName: "Commit Updated Icons"
  env:
    UserName: $(GitHubUser)
    Password: $(GitHubPat)
  inputs:
    targetType: 'inline'
    script: 'git config --global user.email "azure-pipeline@materialdesigninxaml.net/"
      
      git config --global user.name "Azure Pipeline"

      git remote set-url origin https://$env:UserName:$env:Password@github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit.git

      git checkout -f pipeline/icons | Write-Host

      git commit -a -m "Icons update from Azure pipeline" | Write-Host
      
      git push -f origin pipeline/icons | Write-Host'

- task: PublishPipelineArtifact@0
  name: "PublishResourceGenerator"
  enabled: "false"
  inputs:
    artifactName: 'ResourceGenerator'
    targetPath: 'mdresgen/bin/Release'