trigger:
- master

pr: none 

pool:
  vmImage: 'VS2017-Win2016'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'Scripts\\GenerateThemesWikiMarkdown.ps1'

- task: WikiUpdaterTask@1
  inputs:
    repo: 'github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit.wiki.git'
    filename: 'ControlStyleList.md'
    dataIsFile: true
    sourceFile: 'Scripts\\ControlStyleList.md'
    message: 'Automatic update of ControlStyleList.md from Azure pipeline'
    gitname: 'Azure Dev Ops'
    gitemail: 'azure@materialdesigninxaml.net'
    user: '$(GitHubUser)'
    password: '$(GitHubPat)'
    localpath: '$(System.DefaultWorkingDirectory)\\Scripts\\Wiki'